import numpy as np
import matplotlib.pyplot as plt


# Load Verlet output generated by spring_verlet.cpp
results = np.loadtxt("trajectories_verlet.txt")
result_E = np.loadtxt("trajectories.txt")

plt.figure(1)
plt.clf()
plt.xlabel("time_V (s)")
plt.grid()
plt.plot(results[:, 0], results[:, 1], label="x (m)")
plt.plot(results[:, 0], results[:, 2], label="v (m/s)")
plt.legend()
plt.show()

plt.figure(2)
plt.clf()
plt.xlabel("time_E (s)")
plt.grid()
plt.plot(results[:, 0], result_E[:, 1], label="x (m)")
plt.plot(results[:, 0], result_E[:, 2], label="v (m/s)")
plt.legend()
plt.show()